name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Alpha APKs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source-next

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean build
        run: ./gradlew clean

      - name: Build Alpha APKs (unsigned)
        run: ./gradlew assembleArm64-v8aAlphaDebug assembleArmeabi-v7aAlphaDebug assembleX86AlphaDebug assembleX86_64AlphaDebug --daemon --parallel

      - name: Move APKs
        run: find . -type f -path '*/build/outputs/apk/*/debug/*.apk' -exec mv {} . \;

      - name: List APKs
        run: ls -lh *.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Alpha-APKs
          path: source-next/*.apk
