name: Build APK

on:
  workflow_dispatch: # Запуск вручную
  push: # Автоматический запуск при пуше в main
    branches:
      - main

jobs:
  build:
    name: Build Alpha APKs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Alpha APKs
        run: |
          ./gradlew assembleArm64-v8aAlphaRelease assembleArmeabi-v7aAlphaRelease assembleX86AlphaRelease assembleX86_64AlphaRelease --daemon --parallel

      - name: Move APKs
        run: find . -type f -path '*/build/outputs/apk/*/release/*.apk' -exec mv {} . \;

      - name: List APKs
        run: ls -lh *.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Alpha-APKs
          path: source/*.apk
